# Generated by Django 5.1.4 on 2024-12-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('zipCode', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('paymentTerms', models.TextField(choices=[('15', '15 Days'), ('30', '30 Days'), ('60', '60 Days')])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid')], default='draft', max_length=7, verbose_name='status')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.RESTRICT, to='invoices.client')),
                ('items', models.ManyToManyField(to='invoices.invoiceitem')),
                ('total', models.DecimalField(default=0, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
